name: Parallel lint and PhpStan

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Validate composer.json and composer.lock
      run: composer validate --strict

    - name: Cache Composer packages
      id: composer-cache
      uses: actions/cache@v3
      with:
        path: vendor
        key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
        restore-keys: |
          ${{ runner.os }}-php-
    - uses: shivammathur/setup-php@v2
      with:
        php-version: 8.1

    - name: Install dev dependencies
      run: composer install --dev

    - name: Run parallel-lint
      run: ./vendor/bin/parallel-lint -e php,phpt --exclude vendor --exclude temp .

    - name: Run phpstan
      run: ./vendor/bin/phpstan analyse -c phpstan.neon -l 5 app
